# Generated by Django 5.2.17 on 2026-08-18 02:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('duration_days', models.PositiveIntegerField(help_text='How many days the plan is valid after purchase.')),
                ('sessions_included', models.PositiveIntegerField(default=0, help_text='Number of mentoring sessions included (0 for signal-only plans).')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('specialization', models.CharField(choices=[('Forex', 'Forex'), ('Crypto', 'Crypto'), ('Indices', 'Indices')], default='Forex', max_length=20)),
                ('photo_url', models.URLField(blank=True)),
                ('plans', models.ManyToManyField(blank=True, related_name='mentors', to='mentors.mentorshipplan')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('pair', models.CharField(help_text='e.g. EUR/USD, BTC/USD', max_length=20)),
                ('direction', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=4)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=12)),
                ('stop_loss', models.DecimalField(decimal_places=5, max_digits=12)),
                ('take_profit', models.DecimalField(decimal_places=5, max_digits=12)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='mentors.mentor')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('cancelled', 'Cancelled')], default='open', max_length=12)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='mentors.mentor')),
            ],
            options={
                'verbose_name': 'Time slot',
                'verbose_name_plural': 'Time slots',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
